# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# the default
#pool:
#  vmImage: 'ubuntu-latest'
pool:
  vmImage: 'ubuntu-16.04'
# examples of other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'



#steps:
#    - task: UseDotNet@2
#      inputs:
#        version: '3.0.x'

#    - task: UseDotNet@2
#      inputs:
#        version: '2.2.x'
#        packageType: runtime
